import fs from "node:fs/promises";
import path from "node:path";
import { HarnessReport } from "../core/types.js";

export class MarkdownReporter {
  public static format(report: HarnessReport): string {
    const statusBadge = report.passed ? "✅ **PASSED**" : "❌ **FAILED**";
    const durationSec = (report.metrics.durationMs / 1000).toFixed(2);

    const sections: string[] = [
      `# 🤖 Agent Harness Report: ${report.scenarioName || report.scenarioId}`,
      "",
      `**Result**: ${statusBadge}  `,
      `**Scenario ID**: \`${report.scenarioId}\`  `,
      `**Evaluated At**: \`${report.timestamp}\`  `,
      "",
      "## 📊 Execution Summary",
      "",
      "| Metric | Value |",
      "| :--- | :--- |",
      `| **Status** | ${report.passed ? "Passed" : "Failed"} |`,
      `| **Total Turns** | \`${report.metrics.totalTurns}\` |`,
      `| **Duration** | \`${durationSec}s\` |`,
      `| **Total Tokens** | \`${report.metrics.totalTokens}\` |`,
      `| **Total Cost** | \`$${report.metrics.costUsd.toFixed(4)}\` |`,
      `| **Assertions** | \`${report.metrics.passedAssertions}/${report.metrics.totalAssertions}\` passed |`,
      "",
      "## 🧪 Assertions Breakdown",
      "",
      "| Type | Target | Status | Details |",
      "| :--- | :--- | :---: | :--- |",
    ];

    for (const item of report.assertionResults) {
      const statusIcon = item.passed ? "🟢 Passed" : "🔴 Failed";
      const escapedMsg = (item.message || "").replace(/\|/g, "\\|");
      sections.push(`| \`${item.type}\` | \`${item.target}\` | ${statusIcon} | ${escapedMsg} |`);
    }

    sections.push("");
    sections.push("---");
    sections.push("*Generated by [agent-harness](https://github.com/hirohana77/agent-harness)*");
    sections.push("");

    return sections.join("\n");
  }

  public static async save(report: HarnessReport, outputPath: string): Promise<void> {
    const resolved = path.resolve(outputPath);
    await fs.mkdir(path.dirname(resolved), { recursive: true });
    await fs.writeFile(resolved, this.format(report), "utf8");
  }
}
