import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { TerminalReporter } from "../../src/reporters/terminal.js";
import { JsonReporter } from "../../src/reporters/json.js";
import { MarkdownReporter } from "../../src/reporters/markdown.js";
import { HarnessReport } from "../../src/core/types.js";

describe("Reporters Engine", () => {
  let tempDir: string;

  const mockReport: HarnessReport = {
    scenarioId: "sc-test-01",
    scenarioName: "Test Scenario Feature",
    timestamp: "2026-09-24T00:00:00.000Z",
    passed: true,
    assertionResults: [
      {
        type: "file",
        target: "src/index.ts",
        passed: true,
        message: "File exists",
        durationMs: 2,
      },
      {
        type: "command",
        target: "npm test",
        passed: true,
        message: "Exit code 0",
        durationMs: 15,
      },
    ],
    trajectorySummary: {
      totalTurns: 3,
      totalToolCalls: 2,
      totalTokens: 1500,
      costUsd: 0.0045,
      completed: true,
    },
    metrics: {
      durationMs: 3200,
      totalTurns: 3,
      totalAssertions: 2,
      passedAssertions: 2,
      failedAssertions: 0,
      totalTokens: 1500,
      costUsd: 0.0045,
    },
  };

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "agent-harness-rep-test-"));
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  it("formats terminal report cleanly", () => {
    const output = TerminalReporter.format(mockReport);
    expect(output).toContain("PASS");
    expect(output).toContain("Test Scenario Feature");
    expect(output).toContain("src/index.ts");
    expect(output).toContain("npm test");
  });

  it("formats and saves JSON report", async () => {
    const jsonStr = JsonReporter.format(mockReport);
    const parsed = JSON.parse(jsonStr);
    expect(parsed.scenarioId).toBe("sc-test-01");
    expect(parsed.passed).toBe(true);

    const targetFile = path.join(tempDir, "report.json");
    await JsonReporter.save(mockReport, targetFile);
    const saved = await fs.readFile(targetFile, "utf8");
    expect(JSON.parse(saved).passed).toBe(true);
  });

  it("formats and saves Markdown report", async () => {
    const md = MarkdownReporter.format(mockReport);
    expect(md).toContain("# 🤖 Agent Harness Report");
    expect(md).toContain("PASSED");
    expect(md).toContain("| `src/index.ts` |");

    const targetFile = path.join(tempDir, "report.md");
    await MarkdownReporter.save(mockReport, targetFile);
    const saved = await fs.readFile(targetFile, "utf8");
    expect(saved).toContain("Generated by [agent-harness]");
  });
});
